services:
  strapi:
    build: .
    image: strapi:latest
    container_name: strapi
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./config:/app/config
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env.docker:/app/.env
      - ./public/uploads:/app/public/uploads
    networks:
      - strapi-network
    environment:
      NODE_ENV: development # Default to production ${NODE_ENV:-development} 

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    env_file: .env.docker
    environment:
      - POSTGRES_DB=strapi_investment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wrongdoer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi-network

volumes:
  postgres_data:
    name: strapi-postgres-data

networks:
  strapi-network:
    driver: bridge